/motion_capture_tracking:
  ros__parameters:
    # one of "optitrack", "optitrack_closed_source", "vicon", "qualisys", "nokov", "vrpn", "motionanalysis"
    type: "vicon"
    # Specify the hostname or IP of the computer running the motion capture software
    hostname: "10.157.163.191"

    use_host_time: true
    publish_stamped_poses: true
    broadcast_tf: true
    update_rate: 240.
    # the list of to-be-published stamped poses have two formats:
    # - if each string contains ':', then the first part is the target name defined in the MoCap workspace, the second
    #   part is the wished topic name
    # - if no ':', we then publish the default topic names as "stamped_pose_<target name>"
    publish_stamped_poses_for: ["drone", "obstacle1"]

